adminUser:
  password: vault:tekton-beaver/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  token: vault:tekton-beaver/pipelineUser:token
  username: cagiti-bot
prow:
  hmacToken: vault:tekton-beaver/prow:hmacToken
